# Generated by Django 5.2.6 on 2025-10-16 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_license_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
