# Generated by Django 5.2.6 on 2025-10-16 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_license_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
